---
apiVersion: v1
kind: Service
metadata:
  name: service-clearpoint-frontend
spec:
  selector:
    app: clearpoint-frontend
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
...