apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearpoint-frontend
spec:
  selector:
    matchLabels:
      app: clearpoint-frontend
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: clearpoint-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: clearpoint-frontend
          image: "erandocker/clearpoint_frontend:latest"
      nodeSelector:
        role: frontend
...