name: Deploy-Clearpoint-Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/aws-eks-deployment-frontend.yml
      - EKS_deployments_yaml/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/aws-eks-deployment-frontend.yml
      - EKS_deployments_yaml/*

env:
  K8S_NAMESPACE: applications
  K8S_DEPLOYMENT: clearpoint-frontend
  DOCKER_TAG: latest


jobs:
  deploy-frontend-on-EKS:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./EKS_deployments_yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check pods status befor deployment
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/clearpoint-frontend -n ${{ env.K8S_NAMESPACE }}

      - name: Dedploy clratpoint-frontend
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f frontend-deployment.yaml -n ${{ env.K8S_NAMESPACE }}

      - name: check pods status afteer deployment
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/clearpoint-frontend -n ${{ env.K8S_NAMESPACE }}