on: push
name: Deploy Clearpoint-Fronfend
jobs:
  deploy-frontend-on-eks:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check directory
        working-directory: EKS_deployments_yaml
      run: |
        ls -l
      - name: Check current pods status
        uses: qazz92/kubectl@1.0.3
        env:
          kube_confg_data: ${{ secrets.KUBE_CONFIG_DATA }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        with:
          args: '"get pods -n applications"'